### ISSUE TITLE
API is not uptodate and doesn't contains functoria

### ISSUE THREAD

**Issue by Drup** [mirage/mirage-bushel-www#1]

**Comment by samoht** [comment]
I've just updated http://mirage.github.io/mirage/Mirage.html but unfortunately the result is quite poor. I'm almost in favour of inlining the `.mli`s manually to have a clean documentation which does not mention `Functoria_app` at all...

**Comment by Drup** [comment]
That is weird, does it has the `.cm*` files ?

**Comment by samoht** [comment]
@yallop what do you think? In its current instantiation that doc is not really usable.

@Drup the doc is generated using ocamldoc https://github.com/mirage/mirage/blob/master/Makefile#L53-L57 so I'm not sure we can do better, even with the `cm*` files.

**Comment by Drup** [comment]
Ah, right. I expected you to try with codoc, since the last version of the documentation was using that.

**Comment by samoht** [comment]
I've also just updated http://mirage.github.io/functoria/

**Comment by Drup** [comment]
I have an unsatisfying solution:

```
mkdir /tmp/miragedoc
cp functoria && make doc && cp _build/**/*.odoc /tmp/miragedoc
cp mirage && make doc && cp _build/**/*.odoc /tmp/miragedoc
cp /tmp/miragedoc && ocamldoc -load functoria_app.odoc -load functoria_info.odoc -load functoria_key.odoc -load functoria.odoc -load functoria_runtime.odoc -load mirage_key.odoc -load mirage.odoc -load mirage_runtime.odoc -colorize-code -short-functors -charset utf-8 -html
```

The doc still has indirection, but it is a tiny bit usable.

**Comment by Drup** [comment]
@samoht Can you upload a version with my method ?

**Comment by yomimono** [comment]
I'm archiving this repository, so I think there's no possibility at all for this issue to still be relevant.
